---
name: AntiBlock
version: 1.0.1
description: Block specfic blocks from placing and breaking
main: mzztin\AntiBlock\Main
api: [ 4.0.0 ]
src-namespace-prefix: mzztin\AntiBlock
permissions:
  antiblock.bypass.break:
    default: op
    description: You can break blocks that are blocked
  antiblock.bypass.place:
    default: op
    description: You can place blocks that are blocked
  antiblock.command:
    default: op
    description: You can use the antiblock command

...
